#!/bin/bash

DOTFILES=(.gitconfig .vimrc .bash_profile .zshrc .hammerspoon)

#Remove old dotfiles and replace them
for dotfile in $(echo ${DOTFILES[*]});
do
    sudo rm -rf ~/$(echo $dotfile) &&
    ln -s ~/dotfiles/$(echo $dotfile) ~/$(echo $dotfile) &&
    echo "Linked $dotfile"
done

# Set zsh aliases
rm ~/.oh-my-zsh/custom/me.zsh
ln -s ~/dotfiles/me.zsh ~/.oh-my-zsh/custom/me.zsh &&
echo "Linked .oh-my-zsh/custom/me.zsh"
