#!/bin/bash

DOTFILES=(.gitconfig .vimrc)

#Remove old dotfiles and replace them
for dotfile in $(echo ${DOTFILES[*]});
do
    sudo rm -rf ~/$(echo $dotfile)
    ln -s ~/dotfiles/$(echo $dotfile) ~/$(echo $dotfile)
done
